package com.nantcompany.clipy.navigation

enum class AppRoute(val title: String) {
    SPLASH("Clipy"),
    ONBOARDING("Welcome"),
    HOME("Clipy"),
    PICK_VIDEO("Pick Video"),
    PICK_MULTIPLE_VIDEOS("Pick Multiple Videos"),
    PICK_IMAGES("Pick Images"),
    PICK_AUDIO("Pick Audio"),
    MEDIA_PREVIEW("Media Preview"),
    CUT_VIDEO("Cut Video"),
    COMPRESS_VIDEO("Compress Video"),
    MERGE_VIDEO("Merge Video"),
    EXTRACT_AUDIO("Extract Audio"),
    SLIDESHOW("Slideshow"),
    ROTATE_VIDEO("Rotate Video"),
    SPEED_VIDEO("Speed Control"),
    CROP_VIDEO("Crop Video"),
    FILTERS_VIDEO("Video Filters"),
    REVERSE_VIDEO("Reverse Video"),
    STICKERS_VIDEO("Add Stickers"),
    TEXT_OVERLAY_VIDEO("Text Overlay"),
    PROCESSING("Processing"),
    RESULT("Result"),
    OUTPUT_HISTORY("Output History"),
    VIDEO_PLAYER("Video Player"),
    PRO_EDITOR("Pro Editor"),
    SETTINGS("Settings"),
    FUTURE_TOOLS("More tools coming soon"),
    COMING_SOON_FILTERS("Filters (Soon)"),
    COMING_SOON_STICKERS("Stickers (Soon)"),
    COMING_SOON_TEXT_OVERLAY("Text Overlay (Soon)"),
    COMING_SOON_TIMELINE("Timeline (Soon)"),
    COMING_SOON_TRANSITIONS("Transitions (Soon)"),
    COMING_SOON_AUDIO_EDITOR("Audio Editor (Soon)")
}
